use TestDB
SELECT * FROM CUSTOMER

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)



-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,avg(review_rating) as avg_review
from customer
group by item_purchased
order by avg(review_rating) desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
with cte1 as (select avg(purchase_amount) as avg_purc,shipping_type
from customer
group by shipping_type)
select * from cte1
where shipping_type in('Standard','Express')


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,count(customer_id) as total_num,avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5 item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC

WITH product_discount_stats AS (
    SELECT 
        item_purchased,
        COUNT(*) AS total_purchases,
        SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END) AS discount_purchases
    FROM customer
    GROUP BY item_purchased
)

SELECT TOP 5
   item_purchased,
    total_purchases,
    discount_purchases,
    (discount_purchases * 100.0 / total_purchases) AS discount_percentage
FROM product_discount_stats
ORDER BY discount_percentage ASC
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

--Q11.What is the Purchase Frequency Distribution
SELECT COUNT(*) AS CUSTOMER_COUNT,FREQUENCY_OF_PURCHASES
FROM CUSTOMER
GROUP BY FREQUENCY_OF_PURCHASES

--Q12.Revenue by Product Category
SELECT * FROM CUSTOMER
SELECT category,
       SUM(purchase_amount) AS Total_Sales
FROM customer
GROUP BY category
ORDER BY Total_Sales DESC;

---Q13.Total Revenue
SELECT SUM(purchase_amount) AS Total_Revenue
FROM customer

--Q14,Average Purchase Amount
SELECT AVG(purchase_amount) AS Avg_Purchase
FROM customer

--Q15.Most & Least Purchased Products
SELECT TOP 5 item_purchased,
       COUNT(*) AS Purchase_Count,sum(purchase_amount) as revenue
FROM customer
GROUP BY item_purchased
ORDER BY revenue DESC;

SELECT TOP 5 item_purchased,
       COUNT(*) AS Purchase_Count,sum(purchase_amount) as revenue
FROM customer
GROUP BY item_purchased
ORDER BY revenue ASC;

--Q16.Impact of Discount on Sales
SELECT discount_applied,
       SUM(purchase_amount) AS Total_Sales
FROM customer
GROUP BY discount_applied

--Q17.Seasonal Purchase Trends
SELECT season,
       SUM(purchase_amount) AS Total_Sales
FROM customer
GROUP BY season
ORDER BY Total_Sales DESC;

--Q18.Top Locations by Revenue
SELECT Top 5 location,
       SUM(purchase_amount) AS Total_Revenue
FROM customer
GROUP BY location
ORDER BY Total_Revenue DESC;

--Q19.High Value Customers
SELECT customer_id,
       SUM(purchase_amount) AS Total_Spent
FROM customer
GROUP BY customer_id
ORDER BY Total_Spent DESC;